### ISSUE TITLE
Persona Flutter do not work with Android Devices 

### ISSUE THREAD

**Issue by mrlathiya** [jorgefspereira/persona_flutter#48]
Facing an Animation issue and then trying to start an inquiry on Android devices, it shows the initial spinner and stops abruptly and restarts the app again.

Using persona_flutter: ^3.2.0

Please find below the console logs.

`I/ImeTracker(10196): com.uobo.uobo:45a0686d: onHidden
E/OpenGLRenderer(10196): Unable to match the desired swap behavior.
W/LOTTIE  (10196): Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
W/WindowOnBackDispatcher(10196): sendCancelIfRunning: isInProgress=falsecallback=androidx.activity.OnBackPressedDispatcher$Api33Impl$$ExternalSyntheticLambda0@f7791d4
W/WindowOnBackDispatcher(10196): sendCancelIfRunning: isInProgress=falsecallback=androidx.activity.OnBackPressedDispatcher$Api33Impl$$ExternalSyntheticLambda0@f7791d4
D/EGL_emulation(10196): app_time_stats: avg=5.72ms min=3.08ms max=49.96ms count=62
D/EGL_emulation(10196): app_time_stats: avg=4.52ms min=2.53ms max=5.53ms count=61
D/CompatibilityChangeReporter(10196): Compat change id reported: 171228096; UID 10190; state: ENABLED
W/WindowOnBackDispatcher(10196): sendCancelIfRunning: isInProgress=falsecallback=androidx.activity.OnBackPressedDispatcher$Api33Impl$$ExternalSyntheticLambda0@f7791d4
D/AndroidRuntime(10196): Shutting down VM
E/AndroidRuntime(10196): FATAL EXCEPTION: main
E/AndroidRuntime(10196): Process: com.uobo.uobo, PID: 10196
E/AndroidRuntime(10196): java.lang.NumberFormatException: For input string: "100%"
E/AndroidRuntime(10196):        at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
E/AndroidRuntime(10196):        at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
E/AndroidRuntime(10196):        at java.lang.Double.parseDouble(Double.java:660)
E/AndroidRuntime(10196):        at com.withpersona.sdk2.inquiry.network.dto.ui.UiComponentConfig$RemoteImage.getWidth(UiComponentConfig.kt:306)
E/AndroidRuntime(10196):        at com.withpersona.sdk2.inquiry.steps.ui.styling.ImageStylingKt.applyStyles(ImageStyling.kt:86)
E/AndroidRuntime(10196):        at com.withpersona.sdk2.inquiry.steps.ui.components.RemoteImageComponentKt$remoteImageFromUrl$3$1.invoke(RemoteImageComponent.kt:166)
E/AndroidRuntime(10196):        at com.withpersona.sdk2.inquiry.steps.ui.components.RemoteImageComponentKt$remoteImageFromUrl$3$1.invoke(RemoteImageComponent.kt:165)
E/AndroidRuntime(10196):        at com.withpersona.sdk2.inquiry.steps.ui.components.UiComponentHelper.onLayout(UiComponentHelper.kt:36)
E/AndroidRuntime(10196):        at com.withpersona.sdk2.inquiry.steps.ui.UiStepUtils$generateViewsFromUiScreen$1.invoke(UiStepUtils.kt:210)
E/AndroidRuntime(10196):        at com.withpersona.sdk2.inquiry.steps.ui.UiStepUtils$generateViewsFromUiScreen$1.invoke(UiStepUtils.kt:209)
E/AndroidRuntime(10196):        at com.withpersona.sdk2.inquiry.shared.ui.ViewUtilsKt.addOneShotPreDrawListenerAndDiscardFrame$lambda$0(ViewUtils.kt:10)
E/AndroidRuntime(10196):        at com.withpersona.sdk2.inquiry.shared.ui.ViewUtilsKt.$r8$lambda$o0Y9EzBE--8m3zsRUQyTcs4sHUA(Unknown Source:0)
E/AndroidRuntime(10196):        at com.withpersona.sdk2.inquiry.shared.ui.ViewUtilsKt$$ExternalSyntheticLambda0.run(Unknown Source:2)
E/AndroidRuntime(10196):        at com.withpersona.sdk2.inquiry.shared.ui.OneShotPreDrawListenerWithDiscardedFrame.onPreDraw(OneShotPreDrawListenerWithDiscardedFrame.kt:49)
E/AndroidRuntime(10196):        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1176)
E/AndroidRuntime(10196):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3772)
E/AndroidRuntime(10196):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
E/AndroidRuntime(10196):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
E/AndroidRuntime(10196):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
E/AndroidRuntime(10196):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
E/AndroidRuntime(10196):        at android.view.Choreographer.doCallbacks(Choreographer.java:952)
E/AndroidRuntime(10196):        at android.view.Choreographer.doFrame(Choreographer.java:882)
E/AndroidRuntime(10196):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
E/AndroidRuntime(10196):        at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(10196):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10196):        at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(10196):        at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(10196):        at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(10196):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10196):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(10196):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
I/Process (10196): Sending signal. PID: 10196 SIG: 9
`

**Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().**

**java.lang.NumberFormatException: For input string: "100%"**

I am happy to share any more details if required; thank you in advance.

**Comment by jorgefspereira** [comment]
Hi @mrlathiya seems to be an internal issue with the persona sdk itself. I updated to the newest version. Please give it a try and if it continues report back with more details.

**Comment by abdullah1908** [comment]
@mrlathiya can you please confirm as we're planning to integrate Persona in App using Flutter?

**Comment by abdullah1908** [comment]
@jorgefspereira I have gone through [Reddit thread](https://www.reddit.com/r/FlutterDev/comments/m99y0b/how_to_integrate_external_fingerprint_scanner/) & not sure if this issue still exist with this package? Can you please confirm?
